version: '3'

services:

  postgres-main: 
    image: postgres
    restart: no
    volumes:
      - ./data/main:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB_MAIN}
      - POSTGRES_USER=${POSTGRES_USER_MAIN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MAIN}

  postgres-auth: 
    image: postgres
    restart: no
    volumes:
      - ./data/auth:/var/lib/postgresql/data
    ports:
      - 5489:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB_AUTH}
      - POSTGRES_USER=${POSTGRES_USER_AUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_AUTH}

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080
      
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    restart: no
    command: start-dev
    depends_on:
      - postgres-auth
    env_file:
      - .env
    ports:
      - 8081:8080