version: "3"

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - admin
      - --pass
      - password
    networks:
      - default

networks:
  default:
    driver: bridge
